name: tabddpm_
channels:
  - conda-forge
  - nvidia
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39hd399759_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.8.0=hb921021_15
  - aws-c-cal=0.8.1=h1a47875_3
  - aws-c-common=0.10.6=hb9d3cd8_0
  - aws-c-compression=0.3.0=h4e1184b_5
  - aws-c-event-stream=0.5.0=h7959bf6_11
  - aws-c-http=0.9.2=hefd7a92_4
  - aws-c-io=0.15.3=h173a860_6
  - aws-c-mqtt=0.11.0=h11f4f37_12
  - aws-c-s3=0.7.7=hf454442_0
  - aws-c-sdkutils=0.2.1=h4e1184b_4
  - aws-checksums=0.2.2=h4e1184b_4
  - aws-crt-cpp=0.29.7=hd92328a_7
  - aws-sdk-cpp=1.11.458=hc430e4a_4
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - catalogue=2.0.10=py39hf3d152e_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - cfgv=3.3.1=pyhd8ed1ab_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cloudpathlib=0.21.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - confection=0.1.5=pyhecae5ae_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cymem=2.0.11=py39hf88036b_0
  - cython-blis=0.7.10=py39h44dd56e_2
  - datasets=3.6.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.8.16=py39haef64b4_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - ffmpeg=7.1.0=gpl_he2fd91e_701
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py39h53edacf_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py39h30a5a8d_103
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hf-xet=1.1.8=py39h598437d_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.34.4=pyhd8ed1ab_1
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - identify=2.6.13=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imbalanced-learn=0.12.3=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.29.4=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39hf3d152e_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.4=h3f801dc_0
  - libarrow=16.1.0=h44a453e_49_cpu
  - libarrow-acero=16.1.0=hcb10f89_49_cpu
  - libarrow-dataset=16.1.0=hcb10f89_49_cpu
  - libarrow-substrait=16.1.0=h3ee7192_49_cpu
  - libass=0.17.3=hba53ac1_1
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=16_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran-ng=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_15
  - libgoogle-cloud=2.32.0=h804f50b_0
  - libgoogle-cloud-storage=2.32.0=h0121fbd_0
  - libgrpc=1.67.1=hc2c308b_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.8.0.2=0
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=16.1.0=h081d1f1_49_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libre2-11=2024.07.02=hbbce691_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.1=h029b1ac_0
  - libutf8proc=2.9.0=hb9d3cd8_1
  - libuuid=2.41.2=h5347b49_1
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=1.7.6=cpu_h6728c87_6
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - marisa-trie=1.2.1=py39hf88036b_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2022.1.0=hc2b9512_224
  - multidict=6.6.3=py39h9399b63_0
  - multiprocess=0.70.16=py39h8cd3c5a_1
  - murmurhash=1.0.10=py39hf88036b_2
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.23.5=py39h3d75532_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.0.3=h97ab989_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39hac6e08b_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.8=pyhe01879c_0
  - pre-commit=3.7.0=pyha770c72_0
  - preshed=3.0.9=py39hf88036b_2
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - propcache=0.3.1=py39h9399b63_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=1.7.6=cpu_py39hc68e8b7_6
  - pyarrow=16.1.0=py39he8689d4_6
  - pyarrow-core=16.1.0=py39h6117c73_6_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydantic-core=2.33.2=py39h20260ba_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.9.23=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py39h8cd3c5a_2
  - python_abi=3.9=8_cp39
  - pytorch=1.13.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=27.0.2=py39haa5fa38_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - regex=2025.7.34=py39hd399759_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.0=py39h17f49b6_0
  - s2n=1.5.11=h072c03f_0
  - safetensors=0.6.2=py39h2bddf42_0
  - scipy=1.13.1=py39haf93ffa_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - smart-open=7.3.0.post1=h87fe6b5_0
  - smart_open=7.3.0.post1=pyhe01879c_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - spacy=3.7.5=py39h5cdfbc1_1
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - srsly=2.5.1=py39hf88036b_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.2=py39hd92a3bb_0
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2022.3.0=h8d10470_1
  - terminado=0.18.1=pyh0d859eb_0
  - thinc=8.2.5=py39h5cdfbc1_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tokenizers=0.19.1=py39hc62d755_0
  - torchvision=0.14.1=py39_cu117
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.41.2=pyhd8ed1ab_0
  - typer-slim=0.16.1=pyhe01879c_0
  - typer-slim-standard=0.16.1=h810d63d_0
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ujson=5.10.0=py39hf88036b_1
  - ukkonen=1.0.1=py39h74842e3_5
  - uri-template=1.3.0=pyhd8ed1ab_1
  - virtualenv=20.34.0=pyhd8ed1ab_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.46=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - weasel=0.4.1=pyhd8ed1ab_2
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py39hd399759_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xgboost=1.7.6=cpu_py39hc68e8b7_6
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py39h9399b63_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - accelerate==0.31.0
      - alembic==1.16.5
      - anndata==0.10.9
      - arfpy==0.1.1
      - array-api-compat==1.11.2
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - be-great==0.0.7
      - boto3==1.42.3
      - botocore==1.42.3
      - box==0.1.5
      - category-encoders==2.6.3
      - celltypist==1.7.1
      - click==8.1.7
      - cloudpickle==2.2.1
      - colorlog==6.8.2
      - columnar==1.3.1
      - contourpy==1.3.0
      - copulas==0.9.2
      - ctgan==0.9.1
      - cycler==0.12.1
      - decaf-synthetic-data==0.1.6
      - deepecho==0.5.0
      - deprecated==1.3.1
      - domias==0.0.5
      - et-xmlfile==2.0.0
      - executing==0.8.2
      - faiss-cpu==1.7.4
      - faker==37.12.0
      - fastai==2.7.19
      - fastcore==1.7.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - feather-format==0.4.1
      - fflows==0.0.3
      - fonttools==4.60.1
      - formulaic==1.2.1
      - gdown==5.2.0
      - geomloss==0.2.6
      - get-annotations==0.1.2
      - graphviz==0.21
      - greenlet==3.2.4
      - grpcio==1.76.0
      - icecream==2.1.3
      - igraph==0.11.9
      - importlib-resources==6.5.2
      - inflate64==1.0.4
      - interface-meta==1.3.0
      - jmespath==1.0.1
      - keopscore==2.3
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.5
      - leidenalg==0.11.0
      - lifelines==0.27.7
      - lightning-utilities==0.15.2
      - llvmlite==0.43.0
      - loguru==0.7.2
      - louvain==0.8.2
      - mako==1.3.10
      - markdown==3.9
      - matplotlib==3.9.4
      - monai==1.3.2
      - multivolumefile==0.2.3
      - narwhals==2.13.0
      - natsort==8.4.0
      - networkx==2.8.8
      - nflows==0.14
      - numba==0.60.0
      - opacus==1.4.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optuna==3.6.1
      - pandas==1.5.3
      - pgmpy==1.0.0
      - plotly==5.24.1
      - prdc==0.2
      - protobuf==6.33.1
      - py7zr==1.0.0
      - pybcj==1.0.6
      - pybind11==3.0.1
      - pycox==0.2.3
      - pycryptodomex==3.23.0
      - pydantic==1.10.24
      - pydot==4.0.1
      - pykeops==2.3
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyppmd==1.2.0
      - pyreadr==0.5.4
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pysqlite3-binary==0.5.4.post2
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.5
      - pyts==0.13.0
      - pyzstd==0.18.0
      - rdt==1.18.2
      - redis==7.0.1
      - rich==13.7.1
      - rpy2==3.6.4
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - s3transfer==0.16.0
      - scanpy==1.10.3
      - scib==1.1.7
      - scikit-learn==1.6.1
      - scikit-misc==0.3.1
      - sdmetrics==0.13.0
      - sdv==1.11.0
      - seaborn==0.13.2
      - session-info==1.0.1
      - shap==0.45.1
      - slicer==0.0.8
      - sqlalchemy==2.0.44
      - stdlib-list==0.12.0
      - synthcity==0.2.10
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - texttable==1.7.0
      - timeago==1.0.14
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==1.1.0
      - torchmetrics==1.4.0.post0
      - torchtext==0.14.1
      - torchtuples==0.2.2
      - tsai==0.3.9
      - typer==0.12.3
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap-learn==0.5.9.post2
      - urllib3==1.26.20
      - werkzeug==3.1.4
      - xgbse==0.2.3
prefix: /home/golobs/miniconda3/envs/tabddpm_
