dir_list:
  home: /Users/stevengolob/PycharmProjects/camda_hpc
  data: /Users/stevengolob/Documents/school/PhD/Ghent_project_mia_scRNAseq/data
  data_splits: data_splits
  processed_data: data/processed
  figures: results/figures
  res_files: results/files
  mia_files: results/mia
generator_name: scdesign2
generate: true
train: true
load_from_checkpoint: false
scdesign2_config:
  out_model_path: models/d50
  hvg_path: models
muscat_config:
  out_model_path: models
sc_dist_config:
  noise_level: 0.5
  random_seed: 42
  distribution: Poisson
evaluator_config:
  random_seed: 42
generator_config:
  name: scdesign2_parallel
  experiment_name: scdesign2
dataset_config:
  name: onek1k
  train_count_file: onek1k/train_subset_d50.h5ad
  test_count_file: onek1k/test_subset_d50.h5ad
  synthetic_data_name: synthetic_d50.h5ad
  cell_type_col_name: cell_type
  cell_label_col_name: cell_label
  celltypist_model: data/meta/downloads/Immune_All_High.pkl
  random_seed: 42
